name: Greet Everyone
on: [push]

jobs:
  build:
    name: Notify push
    runs-on: ubuntu-latest
    steps:
      - name: Send message to ms teams
        uses: dhollerbach/github-action-send-message-to-ms-teams@1.0.10
        with:
            webhook: 'https://outlook.office.com/webhook/d2ee2262-c45a-4833-b609-125dbcf79769@534272e4-8556-4ad9-926f-cd0ff7ba288d/IncomingWebhook/1e806c321bd84e09bcd1d5ce52880c28/12314bcf-c1fa-45f0-87fb-cdd68d2ac165'
            message: '${{github.event.pusher.name}} have pushed something to ${{github.repository}}'

